# Makefile for MinGW vesion of .../plt/tek

BIN = c:/usr/bin
CC=gcc

CFLAGS = -O 
OUTLIB = ../out/libout.a
WINLIB = -lwinmm -lkernel32 -luser32 -lgdi32 
TEKOBJ = alfa.o alfmod.o circen.o esccod.o grfmod.o tarc.o tcirc.o \
	tekcat.o tekcvt.o
LIBS = libtek.a $(OUTLIB) $(WINLIB) -lm

XFILES= tektty.exe tekps.exe tektyp.exe tekdbg.exe clr.exe tkm.exe vtm.exe

HFILES= alfcom.h arccom.h alfa.h
CFILES= alfa.c closepl_.c cont_.c erase_.c grfmod.c line_.c move_.c \
	openpl_.c space_.c tekcvt.c alfmod.c esccod.c tcirc.c \
	tarc.c tekcat.c

all: libtek.a $(XFILES)

install: $(XFILES)
	cp *.exe $(BIN)

clean:
	rm -f *.o *.a *.exe *~ $(XFILES)

clr.exe: clr.o 
	gcc $(CFLAGS) -o clr clr.o 

tkm.exe: tkm.o 
	gcc $(CFLAGS) -o tkm tkm.o 

vtm.exe: vtm.o 
	gcc $(CFLAGS) -o vtm vtm.o 

tektyp.exe: tektyp.o libtek.a
	gcc -o tektyp tektyp.o $(LIBS)

tekdbg.exe: tekdbg.o libtek.a
	gcc -o tekdbg tekdbg.o $(LIBS)

tektty.exe: tektty.o libtek.a $(OUTLIB)
	gcc -o tektty tektty.o $(LIBS)

tekps.exe: tekps.o libtek.a $(OUTLIB)
	gcc -o tekps tekps.o $(LIBS)

libtek.a: $(TEKOBJ)
	ar rus libtek.a $(TEKOBJ)

$(OUTLIB) :
	cd ../out
	make libout.a
	cd ../tek

# DO NOT DELETE THIS LINE

alfa.o: alfcom.h font0.x font11.x
alfmod.o: alfcom.h arccom.h
tektyp.o: arccom.h
esccod.o: arccom.h alfcom.h tcom.h
grfmod.o: arccom.h tcom.h
tekhp.o: arccom.h
tarc.o:
tcirc.o: arccom.h tcom.h
tekcvt.o: alfcom.h
tektty.o: arccom.h
tekps.o: arccom.h
tektyp.o: arccom.h
tekdbg.o: arccom.h
