# PLT makefile for MinGW

BIN=c:/usr/bin
CC=gcc

build:
	make -C out
	make -C tplt
	make -C tek
	make -C pltfnt
	echo Compilation complete.

install: build
	make -C out
	make -C tplt install
	make -C pltfnt install
	echo Installation complete.

uninstall:
	rm -f $(BIN)/plt.exe

clean:
	make -C out clean
	make -C tplt clean
	make -C tek clean
	make -C pltfnt clean
	rm -f bin/[a-z]* *~ *.exe *.EXE

empty: clean
	rm -f demo/*.exe demo/*.bak demo/wplt.*
	rm -f demo/*.EXE demo/*.BAK demo/WPLT.*

version:
	perl version.pl

pltsc.zip: clean version 
	rm -f pltsc.zip demo/*.exe demo/*.bak
	zip pltsc readme.sc plt.sh makefile.*
	zip pltsc configure configure.bat
	zip pltsc imp/makefile.* imp/*.c 
	zip pltsc out/makefile.* out/*.c out/*.cpp out/*.h out/*.txt 
	zip pltsc pltfnt/makefile.* pltfnt/*.c pltfnt/*.h pltfnt/*.mph 
	zip pltsc pltfnt/*.txt
	zip pltsc tek/makefile.* tek/*.c tek/*.h tek/*.x tek/*.tek
	zip pltsc tplt/makefile.* tplt/*.c tplt/*.h tplt/*.txt
	zip pltsc plots/*.*
	zip pltsc man/Makefile man/*.*
	zip pltsc demo/*.*
	zip pltsc VS18/*.sln VS18/*.vcxproj VS18/*.filters VS18/*.txt 
	zip pltsc VS18/*.rc VS18/*.ico VS18/*.def 
	zip pltsc VS18/*.hh* VS18/demo/*.htm
	zip pltsc version.pl plt.iss
	make -C mplt clean update
	zip -r pltsc mplt
	zip pltsc mplt/Makefile mplt/*/*.txt
	zip -r pltsc mplt/*.lproj mplt/*.pmdoc mplt/*.xcodeproj

plt.zip:
	rm -f plt.zip 
	rm -f demo/*.exe demo/*.bak demo/*.man demo/wplt.*
	cp man/pltpc.txt demo/plt.man
	cp c:/usr/bin/plt.exe demo
	cp c:/usr/bin/pltfnt.exe demo
	zip -j plt demo/*.*

plt-win.zip: version
	rm -f demo/*.exe demo/*.bak demo/*.man demo/wplt.*
	../setup/iscc plt.iss
	zip -j plt-win Output/setup.exe VS18/readme.txt
	rm -rf Output

zipsrc: pltsc.zip 
zipdem: plt.zip
setup: plt-win.zip 
dist: pltsc.zip plt.zip plt-win.zip
	cp -f pltsc.zip plt.zip plt-win.zip ../dist
	rm -f pltsc.zip plt.zip plt-win.zip

