BIN = /usr/local/bin
VERSION = local
CFLAGS = -O -DUNIX -DNEXT -DDEBUG
C = -DUNIX

# The following functions are required from the UNIX C math library:
#	floor, pow, log10, ceil, sqrt

OUTLIB = ../out/libout.a -lNeXT_s -lsys_s -ldpsops -lm

PLT_O= axanno.o axes1.o axes2.o axes3.o axes4.o axes5.o \
	axgrid.o axline.o axtick.o \
	bindat.o cnglun.o dattim.o defpar.o doplot.o errbar.o \
	filetime.o getdat.o getmsg.o getnum.o getstr.o histo.o \
	ifmt.o indata.o indx.o iscan.o \
	labchr.o label.o labpos.o linetp.o linplt.o lookup.o \
	namfil.o numb2.o nxtlin.o opninc.o pltkey.o polygon.o \
	proces.o putmsg.o rect.o setaxpar.o setprm.o setsiz.o setup.o \
	shadeare.o smooth.o sort.o stnmpm.o sttxpm.o wave.o \
	wrprml.o xpos.o

PLT_C= axanno.c axes1.c axes2.c axes3.c axes4.c axes5.c \
	axgrid.c axline.c axtick.c \
	bindat.c cnglun.c dattim.c defpar.c doplot.c errbar.c \
	filetime.c getdat.c getmsg.c getnum.c getstr.c histo.c \
	ifmt.c indata.c indx.c iscan.c \
	labchr.c label.c labpos.c linetp.c linplt.c lookup.c \
	namfil.c numb2.c nxtlin.c opninc.c pltkey.c polygon.c \
	proces.c putmsg.c rect.c setaxpar.c setprm.c setsiz.c setup.c \
	shadeare.c smooth.c sort.c stnmpm.c sttxpm.c wave.c \
	wrprml.c xpos.c

CFILES= tplt.c $(PLT_C)

HFILES= plt.h pltblk.h fort.h

all: tplt

clean:
	rm -f tplt *.o libplt.a $(PLT_O) core *.exe *.EXE *.aps

install: tplt
	install -m 755 tplt $(BIN)/tplt

tplt: tplt.o libplt.a ../out/libout.a
	cc $(CFLAGS) -o tplt tplt.o libplt.a $(OUTLIB)

libplt.a: $(PLT_O)
	ar ru libplt.a $(PLT_O)
	ranlib -s libplt.a

lint:
	lint  -h -x -a -c $L $C $(CFILES) > lint.log

logo: tplt
	./tplt ../plots/logo

# This searches the C sources and makes dependence rules
depend:
	grep -i '^#include *"' $(CFILES) | \
	sed -e 's/:#include *"/: /' \
	    -e 's/"//' \
	    -e 's/\.c/.o/' \
	    -e 's,../[a-zA-Z]*/,,' | \
	awk ' { if ($$1 != prev) { print rec; rec = $$0; prev = $$1; } \
		else { if (length(rec $$2) > 78) { print rec; rec = $$0; } \
		       else rec = rec " " $$2 } } \
	      END { print rec } ' > makedep
	echo '$$r makedep' >>eddep
	echo '/^# DO NOT DELETE THIS LINE/+1,$$d' >eddep
	echo '$$r makedep' >>eddep
	echo 'w' >>eddep
	cp Makefile Makefile.bak
	ed - Makefile < eddep
	rm eddep makedep

# DO NOT DELETE THIS LINE

tplt.o: plt.h pltblk.h fort.h cincl.h version.h
axanno.o: fort.h plt.h pltblk.h
axes1.o: plt.h pltblk.h fort.h
axes2.o: plt.h pltblk.h fort.h
axes3.o: plt.h pltblk.h
axes4.o: plt.h pltblk.h
axes5.o: plt.h pltblk.h
axgrid.o: plt.h pltblk.h fort.h
axline.o: plt.h pltblk.h fort.h
axtick.o: plt.h pltblk.h fort.h
bindat.o: plt.h pltblk.h cincl.h
cnglun.o: plt.h pltblk.h cincl.h
dattim.o: plt.h pltblk.h
defpar.o: plt.h pltblk.h cincl.h fort.h
doplot.o: plt.h pltblk.h fort.h
filetime.o: plt.h pltblk.h cincl.h fort.h
getmsg.o: plt.h pltblk.h fort.h
getstr.o: plt.h cincl.h
histo.o: plt.h pltblk.h
indata.o: plt.h pltblk.h fort.h
iscan.o: plt.h pltblk.h
labchr.o: plt.h pltblk.h
label.o: plt.h pltblk.h fort.h
labpos.o: plt.h pltblk.h fort.h
linplt.o: plt.h pltblk.h fort.h
lookup.o: plt.h pltblk.h
namfil.o: plt.h pltblk.h
numb2.o: plt.h pltblk.h fort.h
nxtlin.o: plt.h pltblk.h
opninc.o: plt.h pltblk.h cincl.h
pltkey.o: plt.h pltblk.h fort.h
polygon.o: plt.h pltblk.h
proces.o: plt.h pltblk.h fort.h
putmsg.o: plt.h pltblk.h fort.h
rect.o: plt.h pltblk.h
setaxpar.o: plt.h pltblk.h
setprm.o: plt.h pltblk.h fort.h
setsiz.o: plt.h pltblk.h
setup.o: plt.h pltblk.h cincl.h fort.h
shadeare.o: plt.h pltblk.h
stnmpm.o: plt.h pltblk.h fort.h
sttxpm.o: plt.h pltblk.h fort.h
wave.o: plt.h pltblk.h fort.h
wrprml.o: plt.h pltblk.h
xpos.o: plt.h pltblk.h
